FROM nicholasjackson/ubuntu-systemd:latest

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG BUILDPLATFORM
ARG BUILDARCH

# Add Consul
RUN curl -L https://releases.hashicorp.com/consul/1.10.1/consul_1.10.1_linux_${TARGETARCH}.zip -o /tmp/consul.zip && \
    cd /tmp && \
    unzip consul.zip && \
    mv consul /usr/bin/consul && \
    chmod +x /usr/bin/consul

# Install Envoy
RUN curl -L https://github.com/nicholasjackson/envoy-binaries/releases/download/v1.18.3/envoy_1.18.3_linux_${TARGETARCH}.zip -o /tmp/envoy.zip && \
    cd /tmp && \
    unzip envoy.zip && \
    mv envoy /usr/bin/envoy && \
    chmod +x /usr/bin/envoy

# Add fake service binary
RUN curl -L https://github.com/nicholasjackson/fake-service/releases/download/v0.22.7/fake_service_linux_${TARGETARCH}.zip -o /tmp/fake.zip && \
 cd /tmp && \
 unzip fake.zip && \
 mv ./fake-service /usr/bin/fake-service && \
 chmod +x /usr/bin/fake-service

# Start SystemD
CMD ["/sbin/init", "--log-target=journal"]